### ISSUE TITLE
Voip - Instant Messaging implementation

### ISSUE THREAD

**Issue by ftasso** [pquiring/javaforce#11]
Hello,
I really appreciate this VOIP engine and I would like to integrate in my applications but there is a missing feature: the SIP Instant Messaging,
Could you please insert this enhancement in you development plan?

Thank you,
Fabrizio

**Comment by pquiring** [comment]
Sure, let me do some research and get started.

**Comment by ftasso** [comment]
Wonderful! Please, consider me a beta tester

**Comment by pquiring** [comment]
Beta available at https://javaforce.sourceforge.net/beta/
I've tested with FreePBX/Asterisk and the message looks good in Wireshark and I get a 202 but the message is not relayed to the other phone.  Some websites claim FreePBX does NOT support MESSAGE types.  Will try with jfPBX when I get upgrade the server side logic.
Let me know.
Thanks,

**Comment by ftasso** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Wow! Monday I will check your Beta version.I'm using Asterisk/FreePbx since 2013 and IM are fully supported. Thank you,Fabrizio                                                                                                                                             Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: ***@***.***: 13 Ottobre 2023 22:14A: ***@***.*** a: ***@***.***: ***@***.***; ***@***.***: Re: [pquiring/javaforce] Voip - Instant Messaging implementation (Issue #11)  
Beta available at https://javaforce.sourceforge.net/beta/
I've tested with FreePBX/Asterisk and the message looks good in Wireshark and I get a 202 but the message is not relayed to the other phone.  Some websites claim FreePBX does NOT support MESSAGE types.  Will try with jfPBX when I get upgrade the server side logic.
Let me know.
Thanks,

**Comment by pquiring** [comment]
Real busy lately but I've performed some preliminary tests:
 - older Asterisk replies with 202 but does nothing
 - jfPBX is working :)
 - newer Asterisk relays MESSAGE as an INVITE to recipient phone but jfPhone can not answer for some reason ???
More to follow.

**Comment by pquiring** [comment]
Not making much progress on this.  Asterisk MESSAGE support seems to be very buggy.  I may release this "as is" since it works with jfPBX.
Thanks,

**Comment by ftasso** [comment]
Ok Peter,

I will continue to investigate on this issue and I will inform you.


Thank you

**Comment by pquiring** [comment]
If you find any other phone apps with messaging capabilities and get some wireshark logs that may be helpful.

**Comment by pquiring** [comment]
Released JF/48.0 and jfPhone/1.25.  Works with jfPBX but not Asterisk.  Closing for now.

**Comment by ftasso** [comment]
Hello Peter,
I made a new test using the last version you built, the 48.0, and the latest code of JFPhone.

Results:
- I receive correctly all the messages sent from other SIP clients using Asterisk V18
- sending message doesn't workin JFPhone. Please take a look to your IM message:

MESSAGE im:301@192.168.1.211:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.240:5061;branch=z123456-y12345-a330276863349858-1--d12345-;rport
Max-Forwards: 70
Contact: <sip:303@192.168.1.240:5061>
To: "301"<sip:301@192.168.1.211:5060>
From: "303"<sip:303@192.168.1.211:5060>;tag=9d3b9eff2fd32275
Call-ID: 100616d618bb3d403fd
Cseq: 1 MESSAGE
Allow: INVITE, ACK, CANCEL, BYE, REFER, NOTIFY, OPTIONS, MESSAGE
User-Agent: JavaForce/48.0
Content-Type: text/plain
Content-Length: 21

Test message from Fab

It seems wrong the prefix "im:301", my asterisk reply with this: PJSIP syntax error exception when parsing 'Request Line' header on line 1 col 34

Bye,
Fabrizio

**Comment by pquiring** [comment]
Can you past the MESSAGE that is sent from Asterisk so I can compare?

**Comment by ftasso** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hello,tomorrow I will repeat the sequence but the message I posted, retrieved from asterisk log, should be exactly the message you sent.Bye                                                                                                                                             Inviato con Posta in arrivo di BlackBerry Hub+ per Android                                                                                                                                                                           Da: ***@***.***: 9 Novembre 2023 18:13A: ***@***.*** a: ***@***.***: ***@***.***; ***@***.***: Re: [pquiring/javaforce] Voip - Instant Messaging implementation (Issue #11)  
Can you past the MESSAGE that is sent from Asterisk so I can compare?

**Comment by ftasso** [comment]
Hello,
your message from log:

[2023/11/10 13:22:59] Client -> Server
[2023/11/10 13:22:59] MESSAGE im:301@192.168.1.211:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.240:5061;branch=z123456-y12345-11d9f2afba28ddf6-1--d12345-;rport
Max-Forwards: 70
Contact: <sip:303@192.168.1.240:5061>
To: "301"<sip:301@192.168.1.211:5060>
From: "303"<sip:303@192.168.1.211:5060>;tag=28534e5fb94617fc
Call-ID: 77eb3acc18bb92f7f6d
Cseq: 1 MESSAGE
Allow: INVITE, ACK, CANCEL, BYE, REFER, NOTIFY, OPTIONS, MESSAGE
User-Agent: JavaForce/48.0
Content-Type: text/plain
Content-Length: 15

TEST 10/11/2023


using "asterisk -rvvvvvvv"


[2023-11-10 12:22:58] ERROR[2433]: pjproject: <?>:             sip_transport.c Error processing 498 bytes packet from UDP 192.168.1.240:5061 : PJSIP syntax error exception when parsing 'Request Line' header on line 1 col 34:
MESSAGE im:301@192.168.1.211:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.240:5061;branch=z123456-y12345-11d9f2afba28ddf6-1--d12345-;rport
Max-Forwards: 70
Contact: <sip:303@192.168.1.240:5061>
To: "301"<sip:301@192.168.1.211:5060>
From: "303"<sip:303@192.168.1.211:5060>;tag=28534e5fb94617fc
Call-ID: 77eb3acc18bb92f7f6d
Cseq: 1 MESSAGE
Allow: INVITE, ACK, CANCEL, BYE, REFER, NOTIFY, OPTIONS, MESSAGE
User-Agent: JavaForce/48.0
Content-Type: text/plain
Content-Length: 15

TEST 10/11/2023
