### ISSUE TITLE
Subscription anomalies in jfphone on Asterisk 16/18/20

### ISSUE THREAD

**Issue by ftasso** [pquiring/javaforce#17]
Hello,
I have encountered three anomalies during the subscription phase:

1) at the end of the subscription period, the status of the subscribed SIP extension is received, but there is no indication that it relates to the termination of the subscription;

2) if a new subscription is generated before the current one expires, it doesn't overwrite the existing one but creates a new subscription instead. For example, if I open and close the jfphone client 10 times, 10 open subscriptions remain for each monitored extension;

3) when setting the expiry parameter to 0 to cancel the subscription, an error is returned, and the subscription remains active.

Thank you in advance for your support!

**Comment by pquiring** [comment]
This will take some debugging to fix.

**Comment by pquiring** [comment]
Added some code that might help.
https://github.com/pquiring/javaforce/commit/0a1cfe9225684ddb3919593f82b003bbd1eb71f4
But I'm getting error "400 Bad Request" from Asterisk.
Your milage may vary.

**Comment by pquiring** [comment]
One thing the JavaForce VoIP stack does not handle well is SIP dialogs.  According to RFC 3265 the SUBSCRIBE/NOTIFY feature is very dependent on these dialogs (Call-ID header).  Looks like some sort of dialog tracking will be required.  Will take some time to fix this properly.

**Comment by pquiring** [comment]
Just added commit https://github.com/pquiring/javaforce/commit/a2264048093dcdbc16cd30c21f033a8236253bd9 that should allow jfPhone to properly unsubscribe.  It now tracks dialogs for subs.  Looks good but I'll have to test on Monday.

**Comment by ftasso** [comment]
Tomorrow I will also run some tests to verify the unsubscribe phase with the 3 versions of Asterisk I use in my test plan: 16/18/20. Thanks for your valuable support.

Bye,
Fabrizio

**Comment by pquiring** [comment]
Added another commit https://github.com/pquiring/javaforce/commit/c4f1b37ab11ed2241b6c961e8a6388601098cf1c that now handles SUBSCRIBE termination and reSUBSCRIBE properly.

**Comment by pquiring** [comment]
Also the contact list was overhauled in Settings so and previous lists will be deleted.

**Comment by ftasso** [comment]
I have verified the 'sip.resubscribe' by passing the callId returned from the initial 'sip.subscribe', and it works perfectly. The 'sip.unsubscribe' function also works well.

I still have some doubts about the terminated subscribe notification; I believe there is the following issue: in the SIPClient file, the presence message is notified through this line of code: **iface.onNotify(this, callid, event, HTTP.getContent(msg))** however, in BasePhone.java, the subscription termination is parsed on the XML part using the following line: **if (event.equals("presence")) { String substate = HTTP.getParameter(msg, "Subscription-State");** but this parameter is not within the XML block. 

The SIP message appears to be correct: 
[notifymsg.txt](https://github.com/user-attachments/files/17193436/notifymsg.txt)

I still need to investigate further because Asterisk does not always notify the termination of the subscription...

**Comment by pquiring** [comment]
Fixed with JF/69.0 : jfPhone/1.29 : Released on sourceforge.net

**Comment by pquiring** [comment]
You are correct, Subscription-State is NOT in the XML.  It's a header in the SIP headers.
