### ISSUE TITLE
AEC in voip module

### ISSUE THREAD

**Issue by ftasso** [pquiring/javaforce#21]
The VOIP component of JavaForce is truly an impressive software product. I am currently using the G722 codec, which allows for acceptable audio quality in communications. When used with hardware devices (mic/speaker) that implement AEC algorithms, the results are remarkable.
Is there any plan to integrate software AEC algorithms, such as JSpeex, in the future development of the VOIP component?

Thank you,
Fabrizio

**Comment by pquiring** [comment]
Sure, let me look into that.

**Comment by pquiring** [comment]
speex has been implemented but testing will start Monday.

**Comment by ftasso** [comment]
Wow, you were incredibly fast. If you think it would be helpful, I can run some tests before the release.

**Comment by pquiring** [comment]
Sure, I would appreciate that.  I've done some initial testing and seems to work internally at commit https://github.com/pquiring/javaforce/commit/6428e826bc30931c4854f712b8a4a4d2e0e0412b
My SIP provider seems to not support speex though so outbound calls fail (603) but internally seems okay.

**Comment by pquiring** [comment]
I've added speex, speex16 and speex32 but jfPhone only supports 8k and 16k at this time.
Supporting speex32 might take some work.

**Comment by ftasso** [comment]
Hello,
this afternoon I'll try to build jfphone and configure Asterisk to get the new codecs working. I'm really curious to see how it works.

Thanks.

**Comment by pquiring** [comment]
I think speex16,32 are fixed.  The RFC is vague on how that is implemented.  The encoder only accepts 160 samples (default at 8k) so I put two frames for 16k and four frames for 32k into one RTP packet.  Should work.

**Comment by ftasso** [comment]
It took me longer than expected because I preferred to integrate the new Javaforce build directly into my client (I know my source code better and can understand what's happening).
I wasn't able to do real audio tests, as I have an outdated test client that uses ulaw, but I verified that Asterisk correctly recognizes all three versions of Speex:


Tomorrow I'll do some concrete tests.

Thank you

**Comment by pquiring** [comment]
Finally got speex (8,16,32) working with this last commit this morning : https://github.com/pquiring/javaforce/commit/a4df5da40b2b3857ee0d4172c7a8c5f818187b93
I'm running on Asterisk 13.19.1

**Comment by pquiring** [comment]
speex is a lot different that other codecs.  The payload size is variable based on sampling rate and quality parameters.  Lots of changes were needed for that.

**Comment by ftasso** [comment]
The work you did in a weekend is unimaginable!
I'll integrate the files you modified and verify with Asterisk 16/18/20.

**Comment by pquiring** [comment]
I'm going to close this issue for now since jfPhone works for me. 
If you need help integrating with your project we can continue to msg in this issue.

Fixed in JF/70.0 + jfPhone/1.31

Thanks,

**Comment by ftasso** [comment]
Certainly, close the issue. I will update you regarding my integration problem. Thank you for your valuable work.

**Comment by ftasso** [comment]
Hello,
I ran some tests with JFPhone 1.3.1 after downloading it from the internet.
Here’s the test setup:
1) I installed JFPhone on 2 PCs;
2) I selected only speex as the codec (and later only speex16 and olny speex32).
In none of the calls did the audio work correctly, as if something wasn't being activated at the RTP level.

Thank you

**Comment by ftasso** [comment]
Certainly, I use Asterisk and have enabled the Speex codecs. I conducted tests with two versions: FreePBX 16.0.33 - Asterisk 18.20.2 and FreePBX 16.0.40.10 - Asterisk 20.8.1. If you'd like, I can give you access to Asterisk 20 on AWS, accessible via the internet (we can exchange credentials privately). I am at your disposal for any tests.

Thank you

![speex](https://github.com/user-attachments/assets/c2f40779-d5c9-4630-9552-caea7f5da355)

**Comment by pquiring** [comment]
Hmm...let me test again.  Maybe I made a last minute change that broke it.

**Comment by ftasso** [comment]
Good morning, were you able to reproduce the same issue that occurs in my tests?

**Comment by pquiring** [comment]
I will try another test today, thanks.

**Comment by pquiring** [comment]
Tested again and works for me.  Can you use Wireshark to grab a sample call?  Turn off promiscuous mode and use a filter like "HOST 1.2.3.4" with the IP address of your Asterisk host and send to my personal email : pquiring at gmail dot com
Thanks,

**Comment by ftasso** [comment]
Okay, tomorrow I’ll retrieve the network trace of a call with Speex and send it to you. I’ll do the same with another codec, for example G722. Thanks for your support.

**Comment by pquiring** [comment]
Added commit https://github.com/pquiring/javaforce/commit/c48f5d85668bfeb5e49e88aa7fc6d9b7e113e92e that should fix your issue.  When accepting a call jfPhone was not using the RTP payload IDs offered.

**Comment by pquiring** [comment]
Added commit https://github.com/pquiring/javaforce/commit/6b8e36590b3f6b0864f05cdd4cfc4268d0dd6ecd that allows controlling the speex quality in jfPhone.  Might help improve quality.  There are new options in jfPhone in the audio tab related to speex quality.  The default was mid-range.

**Comment by ftasso** [comment]
I really appreciate this change, thank you. I'll run some tests to see which setup performs better.

If it doesn't improve significantly, we can always integrate SpeexDSP... you’ll see, over time we’ll become friends.

**Comment by pquiring** [comment]
I appreciate all the feedback.  Don't work in telecom anymore but I do have Asterisk PBX for our desk phones at my current job.
