### ISSUE TITLE
Question about Instant Messaging

### ISSUE THREAD

**Issue by ftasso** [pquiring/javaforce#22]
In all the versions of Asterisk I tested, messages are only recognized with the 'sip' prefix, otherwise 'im' returns 'unknown technology'. Is it possible to add an attribute within Settings to set a 'sip/im' switch for the single line so it can be propagated to SIPClient?

This is the part of the code where the change would have an impact:

public String message(String to, String[] msg) {
    String callid = getcallid();
    CallDetails cd = getCallDetails(callid);  //new CallDetails
    cd.src.to = new String[]{to, to, remotehost + ":" + remoteport, ":"};
    cd.src.from = new String[]{name, user, remotehost + ":" + remoteport, ":"};
    cd.src.contact = "<sip:" + user + "@" + cd.localhost + ":" + getlocalport() + ">";
// **cd.uri = "im:" + to + "@" + remotehost + ":" + remoteport;**
    cd.uri = "sip:" + to + "@" + remotehost + ":" + remoteport;
    cd.src.from = replacetag(cd.src.from, generatetag());
    cd.src.branch = getbranch();
    cd.src.cseq++;
    cd.sdp = msg;
    if (!issue(cd, "MESSAGE", true, true)) {
      return null;
    }
    return callid;
}

**Comment by pquiring** [comment]
I don't mind just changing it to "sip" if that works.  It's never worked for me yet anyways.  Are there other sip servers that use "im" ?

**Comment by pquiring** [comment]
I could only get instant messaging working with my jfPBX, never Asterisk.

**Comment by ftasso** [comment]
I've always only used Asterisk and open-source SIP clients that implement instant messaging with the 'sip' prefix. ChatGPT says that Kamailio (which I've never heard of) uses the 'im' prefix. For me, the best solution is to make it configurable via Settings.line.

I've prepared some Asterisk scripts for the IM part, with these you should see messaging working with jfphone. The example uses two extensions, 101 and 102, where it's important to set the context for the messages.

![IM](https://github.com/user-attachments/assets/46c419f8-6721-425a-b5a1-d7cc2b553e45)
[im.zip](https://github.com/user-attachments/files/17277372/im.zip)

**Comment by pquiring** [comment]
I've changed it to "sip" for now.  If someone needs "im" I can add that config option at that point.
https://github.com/pquiring/javaforce/commit/8c35fc5366a3482fb3199b47901d2d7d4582c5a9

**Comment by pquiring** [comment]
I've added SIPClient.setMessageURI() in case someone needs to change it.

**Comment by ftasso** [comment]
well, thank you

**Comment by pquiring** [comment]
Fixed in JF/70.0 + jfPhone/1.31

Thanks,
