### ISSUE TITLE
BYE reply with null contact 

### ISSUE THREAD

**Issue by ftasso** [pquiring/javaforce#23]
When the Asterisk server sends the BYE command, the VoIP module returns a response with a null contact tag. The server does not recognize the response as valid and resends the same request multiple times. I am attaching the relevant part of the SIP exchange.

[bye_ack_issue.txt](https://github.com/user-attachments/files/17408698/bye_ack_issue.txt)

Thank you

**Comment by pquiring** [comment]
This should be fixed with commit : https://github.com/pquiring/javaforce/commit/f5011012eedeea2f0e18b4b72e12c4afe9151764

**Comment by ftasso** [comment]
Yes, it works well now.

Thank you

**Comment by pquiring** [comment]
Fixed in JF/71.0
