### ISSUE TITLE
OPTIONS reply implementation

### ISSUE THREAD

**Issue by ftasso** [pquiring/javaforce#24]
Asterisk's Qualify option determines the sending of the OPTIONS command to check the client's availability, and the client itself can use this mechanism to verify the status of the Asterisk server. Is it possible to implement this?

Thank you

**Comment by pquiring** [comment]
Note, had to add another method to SIPClientInterface.

SDP onOptions(SIPClient client,String callid);

**Comment by pquiring** [comment]
RFC 3261 doesn't give much details on the SDP contents.  There is normally a RTP "port" in there that I leave as zero since no resources are actually allocated for this request.

**Comment by ftasso** [comment]
I conducted several tests and the SIP OPTIONS exchange is working correctly.
Tomorrow, I'll perform an additional check that I couldn't do today due to time constraints: I want to ensure that by simulating a crash of the VoIP client, Asterisk invalidates the registration if there is no reply to OPTIONS (after the qualifyFreq timeout).

Thank you

**Comment by ftasso** [comment]
I've verified the registration invalidation on the Asterisk side, and it works: by terminating the client process without performing the unregister, Asterisk changes the endpoint's status to Unreachable after the first OPTIONS command (and subsequent retries) when no response is received.

**Comment by pquiring** [comment]
Fixed in JF/71.0

**Comment by ftasso** [comment]
I was rereading your note regarding the RTP port set to zero, and I had a doubt, so I checked what happens with another SIP client. I'm attaching the trace of the message exchange with Javaforce and one made with MicroSip.
Both work....

[options_trace.txt](https://github.com/user-attachments/files/17449901/options_trace.txt)

**Comment by pquiring** [comment]
This commit https://github.com/pquiring/javaforce/commit/51746c408e04bbe3adacf36e09a90e02f1336b1a should fix that.

**Comment by ftasso** [comment]
yes, it works.

Thank you
