### ISSUE TITLE
JfDatalogger 0.29 ( W10-64)

### ISSUE THREAD

**Issue by SuperJerry69** [pquiring/javaforce#6]
This program look nice but with Modbus TCP or Siemens S7 iso on TCP : i have no request on ethernet ( on wireshark traces )
For modbus tags : what is the syntax ? MW , HR  or something else ?

**Comment by pquiring** [comment]
There is some help here:
http://jfdatalogger.sourceforge.net/help.php

**Comment by pquiring** [comment]
Try disabling IP6 on your network cards.

**Comment by pquiring** [comment]
You shouldn't need the sock4 setting.  For siemens, you put in a host (ip address) and tag right?  Once you have added the tags click on "Run".  Do you see values in the table (right top side) and a graph building (side bottom side) ?
I've only tested on Siemens S7-300 series PLCs (400 series should work too).  Maybe your firewall is blocking the app, try disabling it.

**Comment by pquiring** [comment]
You can run the app from the command line to view log messages.
Install Java from https://adoptopenjdk.net/
Run cmd.exe
Run these commands:
```
  cd c:\program files\jfdatalogger
  java -cp javaforce.jar;jfdatalogger.jar App
```
Paste the output here.

**Comment by pquiring** [comment]
No comment in 3 months, closing issue.
