### ISSUE TITLE
Missing SDP Information

### ISSUE THREAD

**Issue by alexander-her** [pquiring/javaforce#9]
Hello, 

I have a running server using your JavaForce VOIP and a running client. The client is an old testing tool sending a predefined INVITE Message.

I am trying to use your CallDetailsServer.SideDetails class to get the received sdp information.
Unfortunatelly, I cannot find all the entries I need. In this case Session Owner (o=), Session Name (s=) and Start und Endtime (t=).
Is there a possibility to get these entries?

**Comment by pquiring** [comment]
Sure, let me work on that...will take some time.

**Comment by pquiring** [comment]
Implemented with commit 4264856

Let me know if that works for you.

**Comment by pquiring** [comment]
Just realized there was a copy/paste error in that commit.

Here is another commit to fix that : af9374f

**Comment by alexander-her** [comment]
Hi,

thank you for the fast response and adaption. It works for me.
Could I ask, if you could also extend your "buildscp" Method to reuse those entries?

Thanks a lot!

**Comment by pquiring** [comment]
I've made the (t) time start/stop fields setup from values in the CallDetails.SDP struct with commit cd3173a.
But the other fields (o,s) are already setup from other values.

**Comment by alexander-her** [comment]
Hi,

thanks again for the quick response. Your Commit is working for me.
I will close the ticket.
